.\" sport - Slackware Port
.TH "sport" "8" ""  "Klaatu" ""
.SH "NAME"
sport \- Search, research, and install from your collection of SlackBuilds
.SH "SYNOPSIS"
\fBsport\fP [command] [package]
.SH "DESCRIPTION"
.PP 
\fBsport\fP, or "Slackware Port", is a BSD Port style tool that helps
you search through your collection of SlackBuilds, read relevant files
about each SlackBuild, and execute the build and install processes.
.PP
.SH USE CASE AND WORKFLOW
The intended use of \fBsport\fP is the same as [my use of] BSD Port or
Gentoo's Emerge, although the exact commands are unique since the BSD
Port system weilds Makefiles to execute its commands, and Gentoo uses
ebuilds, while SlackBuilds use shell scripts.
.PP
The workflow can be similar: as root, change directory into your
SlackBuild tree, search for the package you wish to install, and then
build and install.
.PP
(Strictly speaking, you do not have to change directory into your
SlackBuilds tree, although if you're used to BSD Ports then you'll
likely do that habitually.)
.SH INSTALLATION
To install sport, use the included SlackBuild file, or just copy sport
to some directory in your path. The recommended location is /usr/sbin
.PP
Copy the man page to /usr/man/man8 and the info page to /usr/info. If
you are reading this, you may have already done that.
.PP
You might need to set the location of your SlackBuild tree by manually
editing /etc/sport.conf, and the source of that tree so that you can
stay in sync with your master branch. You can obtain every script
available on SlackBuilds.org tree using rsync(1). You might place your
SlackBuild tree in /usr/ports, or perhaps /usr/slackbuilds, to mimic
the common BSD Ports location or you may already have a
tree in /var/lib/sbopkg/SBo/??.?  if you are already an sbopkg user.
.PP
Now you are ready to use sport.
.SH COMMANDS
.B search, --search, s, -s
.IP
Performs a fuzzy search for some package. For example\&:
.IP
sport search w3m\&
.IP
Search is always fuzzy and never needs a category or wildcard. It
returns the location within your tree of all matches, plus a brief
description.
.TP
.B list, --list, l, ls, -l
Lists the contents of your SlackBuild tree. Without arguments, it
lists everything in the base path, for example\&:
.IP
sport list\&
.IP
Or you can provide a folder from within your base path\&:
.IP
sport list audio\& | less
.IP
would list all the contents of the audio directory within your
SlackBuild tree. You will probably want to pipe this through less(1).
.PP
.TP 
.B cat, --cat, c, -c
Displays the README and \&.info files of some package. You want to
do this before building, since the README provides optional dependency
information and build instructions, and the .info file provides
required dependencies.
.IP
Obviously if the package you want to install has dependencies, you
should resolve those dependencies before continuing. Unlike the BSD
Ports systems, \fBsport\fP does NOT resolve dependencies for you.
.IP
The cat command will untar the SlackBuild directory if needed.
.IP
Assuming the package name is unique:
.IP
# sport cat ophcrack 
.IP
If there are multiple matches, then you will need to provide the path
to the package from your SBOPATH (what Gentoo calls the "atom"); for
instance:
.IP
# sport cat network/w3m
.IP
If you are in your SlackBuild tree, you can just provide the atomic
path to the package with a dot-slash:
.IP
# sport cat ./w3m
.IP
You can also provide the current directory as an argument, if you are
currently located in the directory containing the files you with to
cat:
.IP
# sport cat .
.IP 
# sport install --build-only network/w3m
.TP
.B install, --install, i, -i
Downloads the source code (if needed) and executes the SlackBuild for
some package or list of packages, and then by default calls installpkg
to install it to your system.
.IP
As with the \fBcat\fP subcommand, you can provide the path from your
current location if you are in your SlackBuilds tree; otherwise,
provide the path from SBOPATH.
.IP
You can provide a single package name or a list of packages:
.IP
# sport install python-daemon numpy network/w3m
.IP
The \fBinstall\fP option is flexible and can be given an INSTALLER
variable so that you can control what happens after the code is
compiled. The default is to call installpkg, but you could use it to
upgrade packages instead:
.IP
# INSTALLER=upgradepkg install network/w3m 
.IP
Or even something more complex, like:
.IP
# INSTALLER="upgradepkg --install-new" sport i net*/w3m
.B build, --build-only, b, -b
Instead of installing, this only builds the packages, leaving them in
the build directory, never invoking installpkg(8). This is useful if
you run sport on a separate build machine.
.IP
As with \fBcat\fP, you can just provide the package name:
.IP
# sport install --build-only ./w3m
.IP
Unless there are mulitple potential matches, in which case you must
provide the path to the package from your SBOPATH. For instance:
.IP
.TP 
.B check, --check, k, -k
Checks /var/log/packages to see if a package is installed. Very fuzzy
search; not meant to replace pkgtool, just a convenience.
.TP
.B queue, --queue, q, -q
Processes a queue or batch file.
.IP
Creating a queue file is simple. Just list the packages in the order
you wish them to be installed in a plain text file, one package per
line. It is safest to use both the category and package name but if
the package name is unique you can list it alone.
.IP
For example, in a file arbitrarily called w3m.list, you may place some
lines of package names:
.RS
.sp
gc
.br
imlib2
.br
w3m
.RE       
.IP
Parsing is 100% strict in a queue file so you don't have to provide
category names if you don't want it.
.IP
To process this queue file, you would use:
.IP
# sport queue w3m.list
.IP
You will probably find yourself building a queue file from top down,
listing packages starting from the thing you actually want to install
down to the very first thing you actually must install for the builds
to work. In this case, you will want to process the queue file in
reverse. The easiest way to do this is to generate an upside-down
queue file:
.IP
# tac w3m.list > w3m.tac && sport q w3m.tac
.IP
By default, sport only builds the packages in a queue and does not install
them. To make sport install the packages after it builds each one,
pass an INSTALLER variable:
.IP
# INSTALLER=installpkg sport queue w3m.list
.IP
You can utilize this to upgrade a sequence of packages; if you are
upgrading ffmpeg, for instance, and want to also upgrade all of its
many codecs, you could create a queue file that will rebuild all of
the necessary componenets:
.IP
# MAKEOPTS="-j6" INSTALLER=upgradepkg sport q ffmpeg.list
.PP
.TP
.B clean, --clean, n, -n
Removes the directory containing the source code and SlackBuild. It of
course leaves any compressed copy of your SlackBuild directory (the
SlackBuild.org structure). If you are not using the SlackBuild.org
tree, then you should either keep your originals as compressed
archives or do you should probably not use the \fBclean\fP command.
.IP
The order in which you use \fBclean\fP matters. Do you want to clean the
sources first and then install? 
.IP
# sport clean install numpy
.IP
Or do you mean to install first, and then clean?
.IP
# sport install numpy clean
.TP
.B rsync, --rsync, r, -r
Synchronizes your local tree with your source tree, as defined in the
sport script itself. This is no different than doing a manual
rsync, it only offers the convenience of not having to type in the
paths every time you want to sync. 
.IP
# sport rsync
.IP
Pulls in any updates for your tree via rsync.
.IP
Because it does not make sense install something and then sync your
source tree, rsync always runs first. If for some reason you want to
install someting and then rsync, use the commands separately.
.TP
.B version, --version, v, -v
Returns the version of Slackport that you have installed. Also, if
there is an internet connection available, checks to see if a new
version is available. Helpful, no?

.SH CUSTOMIZING BUILD SCRIPTS
.PP
Let's say you want to make some custom changes to a SlackBuild. For
example, you might need to build GraphicsMagick without X11 support
for a server without X libs installed.
.PP
In this case, you would cd to your SlackBuilds directory, untar the
GraphicsMagick tarball, modify the SlackBuild, and then run sport -i
or sport -b. By default, sport does not clobber an existing unarchived
version of a SlackBuild.
.PP
To clear out customized scripts, you can remove the directory manually
or use 'sport clean', although sport clears ALL untarred directories,
so if you have customized versions that you want to keep, you should
not use that.

.SH UPDATES
.TP
Updating applications in Slackware is usually done with
.PP
# upgradepkg /tmp/example-0.2-noarch-1_SBo.tgz
.PP
Updating via sport is no different. For example, if version 99 of
sport has just been released, you would download it and use sport to build
it:
.PP
# sport build ./sport.SlackBuild
.PP
And then use upgradepkg to install:
.PP
# upgradepkg /tmp/sport*99*tgz 

.SH "SEE ALSO"
.nf
.I slackpkg (8)
.I pkgtool (8)
.I installpkg (8)
.URL http://slackermedia.info/sport
.URL http://gitorious.org/slackport
.fi

.PP
.SH "AUTHORS"
.nf
Klaatu (klaatu@member.fsf.org)
.fi

.PP
.SH "BUGS"
Report via email or on gitorious.org. Also feel free to fix them and
request a merge.
.fi
